{
	"id": "CVE-2022-0329",
	"sourceIdentifier": "security@huntr.dev",
	"vulnStatus": "Rejected",
	"published": "2022-01-21T11:15:07.680",
	"lastModified": "2023-11-07T03:41:12.753",
	"descriptions": [
		{
			"lang": "en",
			"value": "Rejected reason: DO NOT USE THIS CANDIDATE NUMBER. Reason: This CVE has been rejected as it was incorrectly assigned. All references and descriptions in this candidate have been removed to prevent accidental usage"
		}
	],
	"references": [],
	"metrics": {},
	"vcConfigurations": [
		{
			"nodes": [
				{
					"operator": "",
					"cpeMatch": [
						{
							"vulnerable": true,
							"criteria": "cpe:2.3:a:loguru_project:loguru:*:*:*:*:*:*:*:*",
							"matchCriteriaId": "",
							"versionEndIncluding": "0.5.3"
						}
					]
				}
			]
		}
	],
	"vcVulnerableCPEs": [
		"cpe:2.3:a:loguru_project:loguru:0.0.1:*:*:*:*:python:*:*",
		"cpe:2.3:a:loguru_project:loguru:0.1.0:*:*:*:*:python:*:*",
		"cpe:2.3:a:loguru_project:loguru:0.2.0:*:*:*:*:python:*:*",
		"cpe:2.3:a:loguru_project:loguru:0.2.1:*:*:*:*:python:*:*",
		"cpe:2.3:a:loguru_project:loguru:0.2.2:*:*:*:*:python:*:*",
		"cpe:2.3:a:loguru_project:loguru:0.2.3:*:*:*:*:python:*:*",
		"cpe:2.3:a:loguru_project:loguru:0.2.4:*:*:*:*:python:*:*",
		"cpe:2.3:a:loguru_project:loguru:0.2.5:*:*:*:*:python:*:*",
		"cpe:2.3:a:loguru_project:loguru:0.3.0:*:*:*:*:python:*:*",
		"cpe:2.3:a:loguru_project:loguru:0.3.1:*:*:*:*:python:*:*",
		"cpe:2.3:a:loguru_project:loguru:0.3.2:*:*:*:*:python:*:*",
		"cpe:2.3:a:loguru_project:loguru:0.4.0:*:*:*:*:python:*:*",
		"cpe:2.3:a:loguru_project:loguru:0.4.1:*:*:*:*:python:*:*",
		"cpe:2.3:a:loguru_project:loguru:0.5.0:*:*:*:*:python:*:*",
		"cpe:2.3:a:loguru_project:loguru:0.5.1:*:*:*:*:python:*:*",
		"cpe:2.3:a:loguru_project:loguru:0.5.2:*:*:*:*:python:*:*",
		"cpe:2.3:a:loguru_project:loguru:0.5.3:*:*:*:*:*:*:*",
		"cpe:2.3:a:loguru_project:loguru:0.5.3:*:*:*:*:python:*:*"
	]
}
